mavenCoordinate:
  group: io.pravega.examples.video
  artifact: flinkprocessor
  version: 0.1.0

FlinkObjectDetectorJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "true"
  input:
    stream: object-detector-input-video
    minNumSegments: 1
  output:
    stream: object-detector-output-video
    minNumSegments: 1
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 2G
    cpu: 500m
    heap: 600m
    taskSlots: 2


FlinkFaceRecognizerJob:
  enabled: true
  parallelism: 1
  enableOperatorChaining: "true"
  input:
    stream: object-detector-input-video
    minNumSegments: 1
  output:
    stream: object-detector-output-video
    minNumSegments: 1
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 2G
    cpu: 500m
    heap: 700m
    taskSlots: 2

VideoDataGeneratorJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "true"
  output:
    stream: object-detector-input-video
    minNumSegments: 1
  useCachedFrame: "false"
  numCameras: 1
  imageWidth: 600
  framesPerSec: 3.0
  chunkSizeBytes: 100000
  taskManager:
    replicas: 1
    heap: 500m
    memory: 2G
    cpu: 500m
    taskSlots: 1

MultiVideoGridJob:
  enabled: false
  parallelism: 1
  readerParallelism: -1
  enableOperatorChaining: "false"
  input:
    stream: generated-video
    minNumSegments: 1
  output:
    stream: grid-video
    minNumSegments: 1
  imageWidth: 75
  framesPerSec: 1.0
  chunkSizeBytes: 524288
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  checkpointIntervalMs: 300000
  taskManager:
    replicas: 1
    memory: 8G
    cpu: 1000m
    taskSlots: 4

VideoReaderJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "false"
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 1G
    cpu: 250m
    taskSlots: 1


